workflows:
  flutter-android:
    name: Build Flutter Android
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Create Android folder if missing
        script: |
          if [ ! -d "android" ]; then
            flutter create .
          fi

      - name: Get dependencies
        script: flutter pub get

      - name: Build debug APK
        script: flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
