workflows:
  android:
    name: Build Android
    max_build_duration: 60
    environment:
      flutter: stable

    scripts:
      - name: Create android folder if missing
        script: |
          if [ ! -d "android" ]; then
            flutter create .
          fi

      - name: Ensure google-services.json is in correct place
        script: |
          if [ -f "google-services.json" ]; then
            echo "Copying google-services.json to android/app/"
            mkdir -p android/app
            cp google-services.json android/app/google-services.json
          else
            echo "google-services.json NOT FOUND!"
          fi

      - name: Build debug APK
        script: flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
