workflows:
  android-workflow:
    name: Android Build Workflow
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Prepare Android directory if missing
        script: |
          if [ ! -d "android" ]; then
            flutter create .
          fi
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Copy google-services.json
        script: |
          echo "Checking google-services.json"
          if [ -f "google-services.json" ]; then
            echo "Found google-services.json, copying to android/app/"
            mkdir -p android/app
            cp google-services.json android/app/google-services.json
          else
            echo "google-services.json NOT FOUND!"
            exit 1
          fi
      - name: Build APK
        script: |
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
