workflows:
  flutter-android:
    name: Build Flutter Android
    environment:
      flutter: stable
    scripts:
      - name: Setup Flutter project
        script: |
          flutter create .
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build debug APK
        script: |
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
